src/components/layout/content/Content.tsx

fix(style): <main> fix the floating layer

---

storybook/config.ts
storybook/package.json
storybook/pnpm-lock.yaml
storybook/src/glob.tsx
storybook/vite.config.mts

fix: macros

---

Dockerfile
docker-compose.yml

I plan to add a Dockerfile for possible local deployment needs.
The temporary process is as follows
1. Change the `.env.template` file
2. docker build
```
docker build -t shiro . --load       
```
3. docker run
```
docker run --name shiro -d -p 2233:3000 shiro
```
I studied the next packaging and temporarily cannot put the NEXT env in the environment variables of docker run. I can only package it locally first.

ci: add Dockerfile

---

README.md

docs: add docker deployment into readme

---

src/components/ui/markdown/Markdown.tsx
src/components/ui/markdown/renderers/footnotes.tsx

✨ feat: Optimize Footnote Display
#84 
Incorporate a button at the location where detailed footnote content is displayed at the bottom of the page for quick return to the main text and highlight the relevant paragraph.

✨ feat: Optimize Footnote Display

---

src/components/widgets/shared/Tweet.tsx

Use `TwitterComponents` instead `TweetComponents` which is deprecated in latest `react-tweet`.
[Deprecated `TweetComponents`](https://github.com/vercel/react-tweet/blob/1592c890641baa12e280c8c0420690624643a32a/packages/react-tweet/src/twitter-theme/types.tsx#L14-L17)

chore(component): remove deprecated type

---

src/styles/scrollbar.css

fix: scrollbar bug in dark mode

---

ecosystem.config.js
ecosystem.standalone.config.js

feat: add pm2 log datetime format

---

src/hooks/shared/use-read-percent.ts
src/providers/shared/WrappedElementProvider.tsx

chore: typo

---

src/components/modules/dashboard/editor/Milkdown/index.module.css

chore: remove duplicate css

---

src/components/modules/shared/ShareModal.tsx
src/components/modules/toc/TocFAB.tsx
src/components/ui/code-highlighter/CodeHighlighter.tsx

改一些提示，看起来各地方都更统一一些  
~~不然提示一会中文一会英文看着有点，，，~~
None
None

pref: edit some text

---

src/app/(app)/(home)/page.tsx

Hide the module when it has no data
Before
https://github.com/Innei/Shiro/assets/33956589/507d30f4-9e48-4866-b559-8a112ff80459
After
https://github.com/Innei/Shiro/assets/33956589/b3ffa46d-3a83-44b1-8c5e-d78ec2a370a1

feat: hide module when no data

---

src/components/modules/shared/AsideDonateButton.tsx

fix: donate qrcode map

---

README.md

docs: update example site URL in README

docs: update example site URL in README

---

next.config.mjs

windows 执行 `pnpm build` 报错，存在路径配置问题，因此修复它。

fix: jotai path configuration on windows

---

README.md

个人博客已不再使用Mix-Space与Shiro，移除示例链接。

[Delete]移除Shiro示例链接

---

src/components/modules/project/ProjectIcon.tsx
src/components/modules/project/ProjectList.tsx

fix: projects layout & styles (#399)

---

README.md

chore: remove demo link

---

src/app/global-error.tsx

fix: location reload not working

---

README.md

修改了Shiro README指向的文档链接以适应新版V3文档

Docs: Change Shiro Document link

---

src/components/modules/shared/EmbedGithubFile.tsx
src/components/ui/code-highlighter/CodeHighlighter.tsx
src/components/ui/markdown/renderers/LinkRenderer.tsx

EmbedGithubFile支持带有行号的链接，一并修复了行数过少时留有空白的问题。
无

feat: support hash in github link

---

src/app/api/bangumi/[...all]/route.ts
src/components/ui/link-card/LinkCard.tsx
src/components/ui/link-card/enums.tsx
src/components/ui/markdown/renderers/LinkRenderer.tsx
src/lib/bangumi.ts
src/lib/link-parser.ts

与TMDB实现类似，向LinkCard添加 https://bgm.tv/ 或 https://bangumi.tv/ 支持。
目前支持3种链接
* subject
* character
* person
另外TMDB小小修改了一下，根据用户语言请求对应的TMDB结果。
无

feat: add bangumi support for LinkCard (subject/character/person)

---

package.json
pnpm-lock.yaml

fix: clicking on the social media icon does not redirect
